version: "3.8"

services:
  db:
    image: postgres:14-alpine
    container_name: olive-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data

    networks:
      - default

  olive:
    image: olive-api-arm64:0.5.0
    container_name: olive-api
    ports:
      - 3000:3000
      - 4000:4000
    command:
      - /bin/sh
      - -c
      - |
        ./olive-admin --db-host=olive-db:5432 migrate
        ./olive-admin --db-host=olive-db:5432 seed
        ./olive-api --db-host=olive-db:5432
    depends_on:
      - db
    networks:
      - default
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - ./olive:/olive
