version: "3.8"

services:
  db:
    image: postgres:14-alpine
    container_name: olive-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data

    networks:
      - default

  olive:
    image: luxcgo/olive:latest
    container_name: olive-server
    depends_on:
      - db
    ports:
      - 3000:3000
      - 4000:4000
    command:
      [
        "./olive",
        "server",
        "--db-host",
        "olive-db:5432",
        "-l",
        "/downloads",
        "-s",
        "/downloads"
      ]

    networks:
      - default
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - ./downloads:/downloads
