version: "3.8"

services:
  db:
    image: postgres:14-alpine
    container_name: olive-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data

    networks:
      - default

  db-init:
    image: olive-api-arm64:0.5.0
    container_name: olive-db-init
    depends_on:
      - db
    command:
      - /bin/sh
      - -c
      - |
        ./olive admin --db-host=olive-db:5432 migrate
        ./olive admin --db-host=olive-db:5432 seed
    networks:
      - default

  olive:
    image: olive-server-arm64:0.5.0
    container_name: olive-server
    depends_on:
      - db
    ports:
      - 3000:3000
      - 4000:4000
    command:
      [
        "./olive",
        "server",
        "--db-host",
        "olive-db:5432",
        "-l",
        "/olive",
        "-s",
        "/olive"
      ]

    networks:
      - default
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - ./olive:/olive
