apiVersion: v1
kind: Namespace
metadata:
  name: olive-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: olive-pod # Base POD name
  namespace: olive-system
spec:
  selector:
    matchLabels:
      app: olive # Selector for POD name search.
  template:
    metadata:
      labels:
        app: olive
    spec:
      containers:
      # olive-api container configuration
      - name: olive-api
        image: olive-api-image
---
apiVersion: v1
kind: Service
metadata:
  name: olive-service
  namespace: olive-system
spec:
  selector:
    app: olive
  ports:
  - name: olive-api
    port: 3000
    targetPort: olive-api
  - name: olive-api-debug
    port: 4000
    targetPort: olive-api-debug